version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers
      - image: circleci/mysql:8.0.18
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
          - MYSQL_DATABASE: app_development
          - MYSQL_ROOT_HOST: '%'
          - MYSQL_HOST: 127.0.0.1
          - MYSQL_ROOT_PASSWORD: 'root'
        command: |
          mysqld --default-authentication-plugin=mysql_native_password

    working_directory: ~/repo

    steps:
      - checkout

      - run: bundle install
      - run: bin/rails db:create
      - run: bin/rails db:schema:load

      - run: bin/rails test
