version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers
        environment:
          - MYSQL_HOST: 127.0.0.1
          - MYSQL_DATABASE: app_development
          - MYSQL_USERNAME: root
          - MYSQL_PASSWORD: root

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
      - image: circleci/mysql:8.0.18
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
          - MYSQL_DATABASE: app_development
          - MYSQL_ROOT_HOST: '%'
        command: |
          mysqld --default-authentication-plugin=mysql_native_password

    working_directory: ~/repo

    steps:
      - checkout

      # Database setup
      - run: bundle install
      - run: bin/rails db:create
      - run: bin/rails db:schema:load

      # run tests!
      - run: bin/rails test
